services:
  - type: web
    name: sushi-backend
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm run start'
    disk:
      name: persistent-disk
      mountPath: /persistent
    envVars:
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: JWT_SECRET
        value: ${JWT_SECRET}
      - key: STRIPE_SECRET_KEY
        value: ${STRIPE_SECRET_KEY}
      - key: FRONTEND_URL
        value: ${FRONTEND_URL}